
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD ALL AVERAGE MARKS NUMBER SHOW STRING STUDENT TOPPERprogram : statementsstatements : statements statementstatements : statementstatement : ADD STUDENT STRING MARKS NUMBERstatement : SHOW ALLstatement : SHOW STUDENT STRINGstatement : AVERAGEstatement : TOPPER'
    
_lr_action_items = {'ADD':([0,2,3,6,7,8,10,13,15,],[4,4,-3,-7,-8,-2,-5,-6,-4,]),'SHOW':([0,2,3,6,7,8,10,13,15,],[5,5,-3,-7,-8,-2,-5,-6,-4,]),'AVERAGE':([0,2,3,6,7,8,10,13,15,],[6,6,-3,-7,-8,-2,-5,-6,-4,]),'TOPPER':([0,2,3,6,7,8,10,13,15,],[7,7,-3,-7,-8,-2,-5,-6,-4,]),'$end':([1,2,3,6,7,8,10,13,15,],[0,-1,-3,-7,-8,-2,-5,-6,-4,]),'STUDENT':([4,5,],[9,11,]),'ALL':([5,],[10,]),'STRING':([9,11,],[12,13,]),'MARKS':([12,],[14,]),'NUMBER':([14,],[15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','parser.py',81),
  ('statements -> statements statement','statements',2,'p_statements','parser.py',85),
  ('statements -> statement','statements',1,'p_statements_single','parser.py',89),
  ('statement -> ADD STUDENT STRING MARKS NUMBER','statement',5,'p_statement_add','parser.py',93),
  ('statement -> SHOW ALL','statement',2,'p_statement_show_all','parser.py',97),
  ('statement -> SHOW STUDENT STRING','statement',3,'p_statement_show_student','parser.py',101),
  ('statement -> AVERAGE','statement',1,'p_statement_average','parser.py',105),
  ('statement -> TOPPER','statement',1,'p_statement_topper','parser.py',109),
]
